# Generated by Django 4.2.4 on 2023-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='volume',
            field=models.FloatField(),
        ),
    ]
